// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAulWd9Th_sra0qcwdw5r_5ltJcuyU3qmE',
    appId: '1:820353211564:web:79bf0fabb2df54816c1309',
    messagingSenderId: '820353211564',
    projectId: 'aproject-c2a9e',
    authDomain: 'aproject-c2a9e.firebaseapp.com',
    storageBucket: 'aproject-c2a9e.appspot.com',
    measurementId: 'G-TXQXE7YZB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4R3Gdm0ilrTPOXSdJGCdfizxoy5KRfE',
    appId: '1:820353211564:android:73f023761218adeb6c1309',
    messagingSenderId: '820353211564',
    projectId: 'aproject-c2a9e',
    storageBucket: 'aproject-c2a9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRiZ9emMCgvnm_1bDp0ijdOhmYwXz3FH8',
    appId: '1:820353211564:ios:dec8d2b80f1206296c1309',
    messagingSenderId: '820353211564',
    projectId: 'aproject-c2a9e',
    storageBucket: 'aproject-c2a9e.appspot.com',
    iosClientId: '820353211564-5fh6gjsded4aqq3q6j53101239tjlir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.itas274Lab3Tanny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRiZ9emMCgvnm_1bDp0ijdOhmYwXz3FH8',
    appId: '1:820353211564:ios:dec8d2b80f1206296c1309',
    messagingSenderId: '820353211564',
    projectId: 'aproject-c2a9e',
    storageBucket: 'aproject-c2a9e.appspot.com',
    iosClientId: '820353211564-5fh6gjsded4aqq3q6j53101239tjlir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.itas274Lab3Tanny',
  );
}
